const dogs = [
    {
        id: 1,
        breed: "Akita Inu",
        image: "/img/dogs/akita_inu.jpg",
        price: '$999.99',
        rating: 3,
    },
    {
        id: 2,
        breed: "Bulldog",
        image: "/img/dogs/bulldog.jpg",
        price: '$1,999.99',
        rating: 2,
    },
    {
        id: 3,
        breed: "Bull Terrier",
        image: "/img/dogs/bullterrier.jpg",
        price: '$499.99',
        rating: 5,
    },
    {
        id: 4,
        breed: "Chow chow",
        image: "/img/dogs/chowchow.jpg",
        price: '$799.99',
        rating: 1,
    },
    {
        id: 5,
        breed: "Daschund",
        image: "/img/dogs/daschund.webp",
        price: '$800',
        rating: 5,
    },
    {
        id: 6,
        breed: "Chihuahua",
        image: "/img/dogs/chihuahua.jpg",
        price: '$100',
        rating: 5,
    },
    {
        id: 7,
        breed: "Dalmatian",
        image: "/img/dogs/dalmatian.jpg",
        price: '$10,000',
        rating: 3,
    },
    {
        id: 8,
        breed: "Dobermann",
        image: "/img/dogs/dobermann.jpg",
        price: '$1,100',
        rating: 3,
    },
    {
        id: 9,
        breed: "German Shepherd",
        image: "/img/dogs/german_shepherd.jpg",
        price: '$1,999.99',
        rating: 4,
    },
    {
        id: 10,
        breed: "Grey Hound",
        image: "/img/dogs/greyhound.jpg",
        price: '$1,099.99',
        rating: 3,
    },
    {
        id: 11,
        breed: "Havanese",
        image: "/img/dogs/havanese.jpg",
        price: '$999.99',
        rating: 4,
    },
    {
        id: 12,
        breed: "Poodle",
        image: "/img/dogs/poodle.webp",
        price: '$599.59',
        rating: 3,
    },
    {
        id: 13,
        breed: "Rotweiler",
        image: "/img/dogs/rotweiler.jpg",
        price: '$3,899.99',
        rating: 2,
    },
];

export default dogs;